// Generated by Ignite ignite.com/cli

import { StdFee } from "@cosmjs/launchpad";
import { SigningStargateClient, DeliverTxResponse } from "@cosmjs/stargate";
import { EncodeObject, GeneratedType, OfflineSigner, Registry } from "@cosmjs/proto-signing";
import { msgTypes } from './registry';
import { IgniteClient } from "../client"
import { MissingWalletError } from "../helpers"
import { Api } from "./rest";
import { MsgDataConfirmation } from "./types/kvs/kvs/tx";
import { MsgAddressRegistration } from "./types/kvs/kvs/tx";
import { MsgDataProposal } from "./types/kvs/kvs/tx";


export { MsgDataConfirmation, MsgAddressRegistration, MsgDataProposal };

type sendMsgDataConfirmationParams = {
  value: MsgDataConfirmation,
  fee?: StdFee,
  memo?: string
};

type sendMsgAddressRegistrationParams = {
  value: MsgAddressRegistration,
  fee?: StdFee,
  memo?: string
};

type sendMsgDataProposalParams = {
  value: MsgDataProposal,
  fee?: StdFee,
  memo?: string
};


type msgDataConfirmationParams = {
  value: MsgDataConfirmation,
};

type msgAddressRegistrationParams = {
  value: MsgAddressRegistration,
};

type msgDataProposalParams = {
  value: MsgDataProposal,
};


export const registry = new Registry(msgTypes);

const defaultFee = {
  amount: [],
  gas: "200000",
};

interface TxClientOptions {
  addr: string
	prefix: string
	signer?: OfflineSigner
}

export const txClient = ({ signer, prefix, addr }: TxClientOptions = { addr: "http://localhost:26657", prefix: "cosmos" }) => {

  return {
		
		async sendMsgDataConfirmation({ value, fee, memo }: sendMsgDataConfirmationParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgDataConfirmation: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgDataConfirmation({ value: MsgDataConfirmation.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgDataConfirmation: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgAddressRegistration({ value, fee, memo }: sendMsgAddressRegistrationParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgAddressRegistration: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgAddressRegistration({ value: MsgAddressRegistration.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgAddressRegistration: Could not broadcast Tx: '+ e.message)
			}
		},
		
		async sendMsgDataProposal({ value, fee, memo }: sendMsgDataProposalParams): Promise<DeliverTxResponse> {
			if (!signer) {
					throw new Error('TxClient:sendMsgDataProposal: Unable to sign Tx. Signer is not present.')
			}
			try {			
				const { address } = (await signer.getAccounts())[0]; 
				const signingClient = await SigningStargateClient.connectWithSigner(addr,signer,{registry, prefix});
				let msg = this.msgDataProposal({ value: MsgDataProposal.fromPartial(value) })
				return await signingClient.signAndBroadcast(address, [msg], fee ? fee : defaultFee, memo)
			} catch (e: any) {
				throw new Error('TxClient:sendMsgDataProposal: Could not broadcast Tx: '+ e.message)
			}
		},
		
		
		msgDataConfirmation({ value }: msgDataConfirmationParams): EncodeObject {
			try {
				return { typeUrl: "/kvs.kvs.MsgDataConfirmation", value: MsgDataConfirmation.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgDataConfirmation: Could not create message: ' + e.message)
			}
		},
		
		msgAddressRegistration({ value }: msgAddressRegistrationParams): EncodeObject {
			try {
				return { typeUrl: "/kvs.kvs.MsgAddressRegistration", value: MsgAddressRegistration.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgAddressRegistration: Could not create message: ' + e.message)
			}
		},
		
		msgDataProposal({ value }: msgDataProposalParams): EncodeObject {
			try {
				return { typeUrl: "/kvs.kvs.MsgDataProposal", value: MsgDataProposal.fromPartial( value ) }  
			} catch (e: any) {
				throw new Error('TxClient:MsgDataProposal: Could not create message: ' + e.message)
			}
		},
		
	}
};

interface QueryClientOptions {
  addr: string
}

export const queryClient = ({ addr: addr }: QueryClientOptions = { addr: "http://localhost:1317" }) => {
  return new Api({ baseURL: addr });
};

class SDKModule {
	public query: ReturnType<typeof queryClient>;
	public tx: ReturnType<typeof txClient>;
	
	public registry: Array<[string, GeneratedType]> = [];

	constructor(client: IgniteClient) {		
	
		this.query = queryClient({ addr: client.env.apiURL });		
		this.updateTX(client);
		client.on('signer-changed',(signer) => {			
		 this.updateTX(client);
		})
	}
	updateTX(client: IgniteClient) {
    const methods = txClient({
        signer: client.signer,
        addr: client.env.rpcURL,
        prefix: client.env.prefix ?? "cosmos",
    })
	
    this.tx = methods;
    for (let m in methods) {
        this.tx[m] = methods[m].bind(this.tx);
    }
	}
};

const Module = (test: IgniteClient) => {
	return {
		module: {
			KvsKvs: new SDKModule(test)
		},
		registry: msgTypes
  }
}
export default Module;